const matches=[
  {date:'DOM · 17:00',home:'Tuna Luso',away:'Castanhal',h:'TL',a:'CA',score:[1,0]},
  {date:'DOM · 18:30',home:'Águia',away:'Bragantino-PA',h:'AM',a:'BR',score:[2,1]},
  {date:'SEG · 20:00',home:'Cametá',away:'São Francisco',h:'CMT',a:'SF',score:[0,0]}
];
const ranking=[
  {name:'Pedro Silva',initials:'PS',points:42,exact:6,hits:13,pos:1},
  {name:'João Rath',initials:'JR',points:38,exact:5,hits:12,pos:2,me:true},
  {name:'Marina Paes',initials:'MP',points:37,exact:4,hits:14,pos:3},
  {name:'Lucas Lima',initials:'LL',points:31,exact:3,hits:12,pos:4},
  {name:'Rafael Costa',initials:'RC',points:26,exact:2,hits:11,pos:5},
  {name:'Ana Souza',initials:'AS',points:23,exact:3,hits:8,pos:6}
];

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function matchMarkup(m,i){return `<article class="match-card"><div class="match-date"><strong>${m.date.split(' · ')[0]}</strong><small>${m.date.split(' · ')[1]}</small></div><div class="teams-line"><div><span class="mini-crest">${m.h}</span><span class="mini-crest" style="margin-top:4px">${m.a}</span></div><div class="team-names"><span>${m.home}</span><span>${m.away}</span></div><div class="prediction-inputs"><input aria-label="Gols de ${m.home}" type="number" min="0" max="20" value="${m.score[0]}"><span>×</span><input aria-label="Gols de ${m.away}" type="number" min="0" max="20" value="${m.score[1]}"></div></div><button class="save-prediction" data-match="${i}">Salvar palpite</button></article>`}
function rankMarkup(r,full=false){if(full)return `<div class="full-rank-row ${r.me?'me':''}"><strong>${r.pos}º</strong><div class="rank-person"><span class="avatar">${r.initials}</span><span><strong>${r.name}${r.me?' (você)':''}</strong><small>${r.me?'↑ Subiu 1 posição':'— Sem alteração'}</small></span></div><span>${r.exact}</span><span>${r.hits}</span><span>${r.points} pts</span></div>`;return `<div class="rank-row ${r.me?'me':''}"><span>${r.pos}</span><div class="rank-person"><span class="avatar">${r.initials}</span><span><strong>${r.name}${r.me?' (você)':''}</strong><small>${r.exact} exatos</small></span></div><span class="rank-points">${r.points} pts</span></div>`}
function render(){const markup=matches.map(matchMarkup).join('');$('#predictionList').innerHTML=markup;$('#detailMatches').innerHTML=markup;$('#miniRanking').innerHTML=ranking.slice(0,5).map(r=>rankMarkup(r)).join('');$('#detailRanking').innerHTML=ranking.slice(0,5).map(r=>rankMarkup(r)).join('');$('#fullRanking').innerHTML=ranking.map(r=>rankMarkup(r,true)).join('');$('#poolsClone').innerHTML=$$('.pool-card').slice(0,2).map(x=>x.outerHTML).join('');}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function setView(view){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view&&(b.classList.contains('nav-item')||b.closest('.bottom-nav'))));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${view}`)}
render();
document.addEventListener('click',e=>{const viewBtn=e.target.closest('[data-view]');if(viewBtn){e.preventDefault();setView(viewBtn.dataset.view)}const save=e.target.closest('.save-prediction');if(save){save.textContent='Salvo ✓';setTimeout(()=>save.textContent='Salvar palpite',1800);toast('Palpite salvo! Você pode editar até o início da partida.')}});

const dialog=$('#poolDialog');
function openDialog(type){const join=type==='join';$('#dialogEyebrow').textContent=join?'CÓDIGO DE CONVITE':'NOVO BOLÃO';$('#dialogTitle').textContent=join?'Entre no bolão':'Crie sua disputa';$('#dialogText').textContent=join?'Digite o código enviado pelo organizador.':'Dê um nome ao bolão para começar.';$('#dialogLabel').childNodes[0].textContent=join?'Código do convite':'Nome do bolão';$('#dialogInput').placeholder=join?'Ex.: PARAZAO26':'Ex.: Bolão da Faculdade';$('#dialogAction').textContent=join?'Buscar bolão':'Continuar';dialog.showModal();$('#dialogInput').focus()}
$('#createPool').addEventListener('click',()=>openDialog('create'));$('#joinPool').addEventListener('click',()=>openDialog('join'));$('.dialog-close').addEventListener('click',()=>dialog.close());$('#dialogAction').addEventListener('click',()=>{if(!$('#dialogInput').value.trim()){toast('Preencha o campo para continuar.');return}dialog.close();toast('Fluxo demonstrativo concluído!')});
$('#notificationBtn').addEventListener('click',()=>toast('⚽ Gol do Remo! O placar agora é 1 × 0.'));

let liveStep=0;const events=[{minute:72,home:1,away:1,title:'Gol — Paysandu',detail:'Cabeçada após cobrança de escanteio',icon:'⚽'},{minute:78,home:2,away:1,title:'Gol — Remo',detail:'Chute forte de fora da área',icon:'⚽'},{minute:90,home:2,away:1,title:'Fim de jogo',detail:'Remo vence o clássico',icon:'■'}];
function applyLive(step){const ev=events[step];['#homeScore','#liveHomeScore'].forEach(id=>$(id).textContent=ev.home);['#awayScore','#liveAwayScore'].forEach(id=>$(id).textContent=ev.away);$('#matchClock').textContent=ev.minute===90?'ENCERRADO':`${ev.minute}'`;$('#liveClock').textContent=ev.minute===90?'FIM':`${ev.minute}'`;const exact=ev.home===2&&ev.away===1;const correct=(ev.home>ev.away);$('#projectedPoints').textContent=exact?'+5 pontos':correct?'+3 pontos':'0 pontos';$('#liveProjection').textContent=exact?'Placar exato · 5 pts':correct?'Acertando o resultado · 3 pts':'Palpite fora da zona de pontos';$('#liveProjection').style.color=correct?'var(--green)':'var(--red)';$('#timeline').insertAdjacentHTML('afterbegin',`<div><b>${ev.minute===90?'FIM':ev.minute+"'"}</b><span>${ev.icon}</span><p><strong>${ev.title}</strong><small>${ev.detail}</small></p></div>`);toast(`${ev.icon} ${ev.title}! Placar ${ev.home} × ${ev.away}`);if(ev.minute===90){$('#simulateGoal').textContent='Partida encerrada';$('#simulateGoal').disabled=true;$('#eventStatus').textContent='Resultado confirmado'}}
$('#simulateGoal').addEventListener('click',()=>{if(liveStep<events.length)applyLive(liveStep++)});

if(location.hash&&$(location.hash))setView(location.hash.slice(1));

function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const signal=new AbortController();const tool={name:'save_prediction',title:'Salvar palpite',description:'Salva ou atualiza o palpite do usuário de demonstração para uma próxima partida.',inputSchema:{type:'object',properties:{matchIndex:{type:'integer',minimum:0,maximum:2},homeScore:{type:'integer',minimum:0,maximum:20},awayScore:{type:'integer',minimum:0,maximum:20}},required:['matchIndex','homeScore','awayScore'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!Number.isInteger(input?.matchIndex)||!matches[input.matchIndex]||!Number.isInteger(input.homeScore)||!Number.isInteger(input.awayScore))throw new Error('Palpite inválido');matches[input.matchIndex].score=[input.homeScore,input.awayScore];render();toast('Palpite atualizado pelo assistente.');return{status:'saved',match:matches[input.matchIndex].home+' x '+matches[input.matchIndex].away,prediction:`${input.homeScore} x ${input.awayScore}`}}};try{Promise.resolve(ctx.registerTool(tool,{signal:signal.signal})).catch(()=>{})}catch(e){}}
registerWebMCP();
